before_script:
  - sudo apt-get update -y && sudo apt-get install m4 autoconf -y

ocaml-4.06:
  image: ocaml/opam:ubuntu-lts-ocaml-4.06
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.07:
  image: ocaml/opam:ubuntu-lts-ocaml-4.07
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.08:
  image: ocaml/opam:ubuntu-lts-ocaml-4.08
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.09:
  image: ocaml/opam:ubuntu-lts-ocaml-4.09
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.10:
  image: ocaml/opam:ubuntu-lts-ocaml-4.10
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.11:
  image: ocaml/opam:ubuntu-lts-ocaml-4.11
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.12:
  image: ocaml/opam:ubuntu-lts-ocaml-4.12
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.13:
  image: ocaml/opam:ubuntu-lts-ocaml-4.13
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-4.14:
  image: ocaml/opam:ubuntu-lts-ocaml-4.14
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-5.0:
  image: ocaml/opam:ubuntu-lts-ocaml-5.0
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam

ocaml-5.1:
  image: ocaml/opam:ubuntu-lts-ocaml-5.1
  script:
    - opam install ./plato.opam --deps-only -t
    - dune runtest
    - opam install ./plato.opam
